In [1]:
import numpy as np


In [2]:
print(np.__version__)

1.24.3


In [3]:
l = [1,2,3,4,5,6,7,8,9]
x = np.array(l)
print(x)
print(type(x))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
print(x+5)
print(x-5)
print(x/5)
print(x*5)

[ 6  7  8  9 10 11 12 13 14]
[-4 -3 -2 -1  0  1  2  3  4]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[ 5 10 15 20 25 30 35 40 45]


In [5]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a+b
print(c)

[ 7  9 11 13 15]


In [6]:
a = np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [7]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print(a.shape)

(2, 5)


In [12]:
a = np.array([[[1,2,3],[4,5,0]],
             [[6,7,8],[9,10,0]]])
print(a.shape)

(2, 2, 3)


In [13]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print(a.reshape(3,2))
print(a.reshape(1,6))
print(a.reshape(3,2))
print(a.reshape(6,1))

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [17]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2,3],
              [4,5,6]])
c = a+b
print(c)

[[ 2  4  6]
 [ 8 10 12]]


In [19]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7,8,9],
              [0,4,6]])
np.hstack((a,b))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 4, 6]])

In [21]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2,3],
              [4,5,6]])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
print(np.random.rand(2,2))

[[0.59852937 0.57671365]
 [0.21470475 0.61603828]]


In [26]:
print(np.random.randint(0,10,size =[5,5]))

[[0 7 1 9 3]
 [0 6 5 8 1]
 [6 5 0 2 4]
 [1 5 7 7 2]
 [1 7 2 8 2]]


In [27]:
print(np.random.random())

0.03174720639873074


In [28]:
print(np.random.random(size = [2,2]))

[[0.13934896 0.57742595]
 [0.59945688 0.00704387]]


In [30]:
print(np.random.choice(['a','e','i','o','u'],size =[ 10,4]))

[['u' 'e' 'u' 'e']
 ['o' 'o' 'e' 'o']
 ['u' 'i' 'i' 'a']
 ['e' 'u' 'u' 'o']
 ['i' 'u' 'a' 'e']
 ['e' 'e' 'e' 'a']
 ['o' 'e' 'u' 'a']
 ['e' 'u' 'i' 'a']
 ['e' 'i' 'u' 'i']
 ['i' 'o' 'a' 'o']]


In [31]:
print(np.random.choice(['a','e','i','o','u'],size = 10,p=[0.3,0.1,0.1,0.4,0.1]))

['e' 'a' 'o' 'a' 'i' 'a' 'a' 'e' 'a' 'e']


In [32]:
(np.random.randint(0,10,size =[5,5]))+1

array([[ 4,  5,  2,  8,  2],
       [ 8,  7, 10,  1, 10],
       [ 9,  1,  2,  3,  8],
       [ 1,  6,  8,  5,  2],
       [ 2,  3,  9,  1,  3]])